spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/db_lock?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    banner: false
    db-config:
      table-underline: true
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.example: debug
    com.example.lock.demo: debug
